![alt text](https://drive.google.com/uc?export=view&id=1UXScsVx_Wni_JuDdB8LeTnM6jsPfIwkW)

Proprietary content. © Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited.

# Sentiment Classification

### Dataset
- Dataset of 50,000 movie reviews from IMDB, labeled by sentiment positive (1) or negative (0)
- Reviews have been preprocessed, and each review is encoded as a sequence of word indexes (integers).
- For convenience, words are indexed by overall frequency in the dataset, so that for instance the integer "3" encodes the 3rd most frequent word in the data. This allows for quick filtering operations such as: "only consider the top 10,000 most common words, but eliminate the top 20 most common words".
- As a convention, "0" does not stand for a specific word, but instead is used to encode any unknown word.

Command to import data
- `from tensorflow.keras.datasets import imdb`

### Import the data (2 Marks)
- Use `imdb.load_data()` method
- Get train and test set
- Take 10000 most frequent words

In [1]:
!pip install tensorflow

In [2]:
#### Add your code here ####
import tensorflow as tf
from tensorflow.keras.datasets import imdb

In [3]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

In [4]:
x_train[0],y_train[0]

([1,
  14,
  22,
  16,
  43,
  530,
  973,
  1622,
  1385,
  65,
  458,
  4468,
  66,
  3941,
  4,
  173,
  36,
  256,
  5,
  25,
  100,
  43,
  838,
  112,
  50,
  670,
  2,
  9,
  35,
  480,
  284,
  5,
  150,
  4,
  172,
  112,
  167,
  2,
  336,
  385,
  39,
  4,
  172,
  4536,
  1111,
  17,
  546,
  38,
  13,
  447,
  4,
  192,
  50,
  16,
  6,
  147,
  2025,
  19,
  14,
  22,
  4,
  1920,
  4613,
  469,
  4,
  22,
  71,
  87,
  12,
  16,
  43,
  530,
  38,
  76,
  15,
  13,
  1247,
  4,
  22,
  17,
  515,
  17,
  12,
  16,
  626,
  18,
  2,
  5,
  62,
  386,
  12,
  8,
  316,
  8,
  106,
  5,
  4,
  2223,
  5244,
  16,
  480,
  66,
  3785,
  33,
  4,
  130,
  12,
  16,
  38,
  619,
  5,
  25,
  124,
  51,
  36,
  135,
  48,
  25,
  1415,
  33,
  6,
  22,
  12,
  215,
  28,
  77,
  52,
  5,
  14,
  407,
  16,
  82,
  2,
  8,
  4,
  107,
  117,
  5952,
  15,
  256,
  4,
  2,
  7,
  3766,
  5,
  723,
  36,
  71,
  43,
  530,
  476,
  26,
  400,
  317,
  46,
  7,
  4,
  2,
  1029,
  

In [5]:
len(x_train[0])

218

### Pad each sentence to be of same length (2 Marks)
- Take maximum sequence length as 300

In [6]:
#### Add your code here ####
e_x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, 
                                                          maxlen=300,
                                                          padding='pre', 
                                                          truncating='post')

In [7]:
e_x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test, 
                                                          maxlen=300,
                                                          padding='pre', 
                                                          truncating='post')

In [8]:
e_x_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,   14,   22,   16,   43,  530,
        973, 1622, 1385,   65,  458, 4468,   66, 3941,    4,  173,   36,
        256,    5,   25,  100,   43,  838,  112,   50,  670,    2,    9,
         35,  480,  284,    5,  150,    4,  172,  112,  167,    2,  336,
        385,   39,    4,  172, 4536, 1111,   17,  546,   38,   13,  447,
          4,  192,   50,   16,    6,  147, 2025,   19,   14,   22,    4,
       1920, 4613,  469,    4,   22,   71,   87,   

### Print shape of features & labels (2 Marks)

Number of review, number of words in each review

In [9]:
#### Add your code here ####
e_x_train.shape,e_x_test.shape

((25000, 300), (25000, 300))

Number of labels

In [10]:
#### Add your code here ####
y_train.shape,y_test.shape

((25000,), (25000,))

### Print value of any one feature and it's label (2 Marks)

Feature value

In [11]:
#### Add your code here ####
e_x_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,   14,   22,   16,   43,  530,
        973, 1622, 1385,   65,  458, 4468,   66, 3941,    4,  173,   36,
        256,    5,   25,  100,   43,  838,  112,   50,  670,    2,    9,
         35,  480,  284,    5,  150,    4,  172,  112,  167,    2,  336,
        385,   39,    4,  172, 4536, 1111,   17,  546,   38,   13,  447,
          4,  192,   50,   16,    6,  147, 2025,   19,   14,   22,    4,
       1920, 4613,  469,    4,   22,   71,   87,   

Label value

In [12]:
#### Add your code here ####
y_train[0]

1

### Decode the feature value to get original sentence (2 Marks)

First, retrieve a dictionary that contains mapping of words to their index in the IMDB dataset

In [13]:
#### Add your code here ####
word_index_dict = tf.keras.datasets.imdb.get_word_index(
    path='imdb_word_index.json'
)
word_index_dict

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

In [43]:
len(word_index_dict)

88584

In [15]:
word_index_dict['as']

14

In [16]:
index_word_dict = dict([(value, key) for key, value in word_index_dict.items()]) 

Now use the dictionary to get the original words from the encodings, for a particular sentence

In [17]:
#### Add your code here ####
en_to_sent = []
for token in e_x_train[0]:
    if token != 0:
        en_to_sent.append(index_word_dict[token])
    
en_to_sent

['the',
 'as',
 'you',
 'with',
 'out',
 'themselves',
 'powerful',
 'lets',
 'loves',
 'their',
 'becomes',
 'reaching',
 'had',
 'journalist',
 'of',
 'lot',
 'from',
 'anyone',
 'to',
 'have',
 'after',
 'out',
 'atmosphere',
 'never',
 'more',
 'room',
 'and',
 'it',
 'so',
 'heart',
 'shows',
 'to',
 'years',
 'of',
 'every',
 'never',
 'going',
 'and',
 'help',
 'moments',
 'or',
 'of',
 'every',
 'chest',
 'visual',
 'movie',
 'except',
 'her',
 'was',
 'several',
 'of',
 'enough',
 'more',
 'with',
 'is',
 'now',
 'current',
 'film',
 'as',
 'you',
 'of',
 'mine',
 'potentially',
 'unfortunately',
 'of',
 'you',
 'than',
 'him',
 'that',
 'with',
 'out',
 'themselves',
 'her',
 'get',
 'for',
 'was',
 'camp',
 'of',
 'you',
 'movie',
 'sometimes',
 'movie',
 'that',
 'with',
 'scary',
 'but',
 'and',
 'to',
 'story',
 'wonderful',
 'that',
 'in',
 'seeing',
 'in',
 'character',
 'to',
 'of',
 '70s',
 'musicians',
 'with',
 'heart',
 'had',
 'shadows',
 'they',
 'of',
 'here',
 

Get the sentiment for the above sentence
- positive (1)
- negative (0)

In [18]:
#### Add your code here ####
y_train[0]

1

### Define model (10 Marks)
- Define a Sequential Model
- Add Embedding layer
  - Embedding layer turns positive integers into dense vectors of fixed size
  - `tensorflow.keras` embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unique integer number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn LabelEncoder.
  - Size of the vocabulary will be 10000
  - Give dimension of the dense embedding as 100
  - Length of input sequences should be 300
- Add LSTM layer
  - Pass value in `return_sequences` as True
- Add a `TimeDistributed` layer with 100 Dense neurons
- Add Flatten layer
- Add Dense layer

In [33]:
#### Add your code here ####
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Flatten, Dropout, Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import TimeDistributed

embedding_vector_length = 100
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=embedding_vector_length, input_length=300))
model.add(LSTM(128,return_sequences=True)) 
model.add(TimeDistributed(Dense(100)))
model.add(Flatten())
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

### Compile the model (2 Marks)
- Use Optimizer as Adam
- Use Binary Crossentropy as loss
- Use Accuracy as metrics

In [34]:
#### Add your code here ####
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

### Print model summary (2 Marks)

In [35]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 300, 100)          1000000   
_________________________________________________________________
lstm_3 (LSTM)                (None, 300, 128)          117248    
_________________________________________________________________
time_distributed_1 (TimeDist (None, 300, 100)          12900     
_________________________________________________________________
flatten_1 (Flatten)          (None, 30000)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 30001     
Total params: 1,160,149
Trainable params: 1,160,149
Non-trainable params: 0
_________________________________________________________________


### Fit the model (2 Marks)

In [36]:
#### Add your code here ####
train_history = model.fit(e_x_train, y_train, batch_size=32,
                          epochs=10,
                          validation_data=(e_x_test, y_test))

Epoch 1/10
782/782 [==============================] - 291s 372ms/step - loss: 0.3669 - accuracy: 0.8308 - val_loss: 0.2984 - val_accuracy: 0.8751
Epoch 2/10
782/782 [==============================] - 404s 516ms/step - loss: 0.1935 - accuracy: 0.9249 - val_loss: 0.3347 - val_accuracy: 0.8662
Epoch 3/10
782/782 [==============================] - 404s 516ms/step - loss: 0.0914 - accuracy: 0.9655 - val_loss: 0.4251 - val_accuracy: 0.8609
Epoch 4/10
782/782 [==============================] - 387s 495ms/step - loss: 0.0297 - accuracy: 0.9892 - val_loss: 0.7317 - val_accuracy: 0.8618
Epoch 5/10
782/782 [==============================] - 437s 559ms/step - loss: 0.0257 - accuracy: 0.9907 - val_loss: 0.7794 - val_accuracy: 0.8525
Epoch 6/10
782/782 [==============================] - 389s 497ms/step - loss: 0.0169 - accuracy: 0.9944 - val_loss: 0.9257 - val_accuracy: 0.8519
Epoch 7/10
782/782 [==============================] - 395s 505ms/step - loss: 0.0164 - accuracy: 0.9944 - val_loss: 0.9760 -

### Evaluate model (2 Marks)

In [37]:
#### Add your code here ####
scores = model.evaluate(e_x_test, y_test, verbose=1)
scores

782/782 [==============================] - 126s 161ms/step - loss: 1.0660 - accuracy: 0.8498


[1.0659786462783813, 0.8497999906539917]

### Predict on one sample (2 Marks)

In [49]:
e_x_test[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [52]:
#### Add your code here ####
predict=model.predict_classes(e_x_test)

In [54]:
# Comparing predicted output of 1st seq with actual output of 1st seq
predict[0],y_test[0]

(array([0]), 0)